# Generated by Django 5.0.3 on 2024-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('name', models.IntegerField()),
                ('place', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
