# Generated by Django 5.0.3 on 2024-04-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_club_games_alter_club_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
